#include "algorithm.h"
#include <iostream>
#include <fstream>

void runAlgorithm1(const std::string& inputFilePath, const std::string& outputFilePath) {
    Graph g = create_graph(inputFilePath);
    g.printEulerTour(outputFilePath);
    std::cout << "Eulerian tour generated by algorithm 1 successfully." << std::endl;
}