#include "algorithm.h"
#include <fstream>
#include <iostream>

void runAlgorithm3(const std::string& inputFilePath, const std::string& outputFilePath) {
    Graph g = create_graph(inputFilePath);
    g.primMST(outputFilePath);
    std::cout << "MST generated by algorithm 3 successfully." << std::endl;
}