#include "algorithm.h"
#include <fstream>
#include <iostream>

void runAlgorithm4(const std::string& inputFilePath, const std::string& outputFilePath) {
    Graph g = create_graph(inputFilePath);
    g.constructHamiltonianCycle(outputFilePath);
    std::cout << "Hamiltonian cycle generated by algorithm 4 successfully." << std::endl;
}