#include "algorithm.h"
#include <fstream>
#include <iostream>

void runAlgorithm5(const std::string& inputFile, const std::string& outputFile) {
    std::string basePath = getExecutablePath();
    // Generate MST and duplicate its edges
    runAlgorithm2(inputFile, basePath + "\\mst");
    Graph g = create_graph(basePath + "\\mst");
    g.duplicateEdgesInMST(basePath + "\\mst", basePath + "\\duplicated_mst");

    // Generate Eulerian tour from the doubled MST
    runAlgorithm1(basePath + "\\duplicated_mst", basePath + "\\eulerian_tour");

    // Convert Eulerian tour to Hamiltonian cycle
    g = create_graph(inputFile);
    Graph e = create_graph(basePath + "\\eulerian_tour");
    e.convertToHamiltonianCycle(g, outputFile);

    std::cout << "Hamiltonian cycle generated by algorithm 5 successfully." << std::endl;
}