#include "algorithm.h"
#include <fstream>
#include <iostream>

void runAlgorithm2(const std::string& inputFilePath, const std::string& outputFilePath) {
    Graph g = create_graph(inputFilePath);
    g.kruskalMST(outputFilePath);
    std::cout << "MST generated by algorithm 2 successfully." << std::endl;
}